version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "15:00"
      timezone: "America/Los_Angeles"
    groups:
      all-dependencies:
        patterns:
          - "*"
    reviewers:
      - "@hxiedwr"
      - "@dwr-zroy"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "15:00"
      timezone: "America/Los_Angeles"
    groups:
      github-action-dependencies:
        patterns:
          - "*"
    reviewers:
      - "@hxiedwr"
      - "@dwr-zroy"