version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      all-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "@hxiedwr"
      - "@dwr-zroy"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-action-dependencies:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
    reviewers:
      - "@hxiedwr"
      - "@dwr-zroy"